language: python
python:
  - '3.6'

before_script:
  - pip install -r requirements.txt
  - psql -c "CREATE DATABASE purbeurre;" -U postgres
  - sudo chmod +x ./manage.py

services:
  - postgresql

script:
  - ./manage.py initdb
  - ./manage.py test