language: python
python:
  - '3.6'
addons:
  firefox: latest

before_script:
  - pip install -r requirements.txt
  - psql -c "CREATE DATABASE purbeurre;" -U postgres
  - psql -c "CREATE USER nmillet WITH PASSWORD 'python123'"
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE purbeurre TO nmillet"
  - psql -c "ALTER USER nmillet CREATEDB"
  - sudo chmod +x ./manage.py
  - ./manage.py migrate
  - ./manage.py initdb
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

services:
  - postgresql

script:
  - ./manage.py test