language: python
python:
  - '3.6'

before_script:
  - pip install -r requirements.txt
  - psql -c "CREATE DATABASE purbeurre;" -U postgres
  - psql -c "CREATE USER nmillet WITH PASSWORD 'python123'"
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE purbeurre TO nmillet"
  - sudo chmod +x ./manage.py

services:
  - postgresql

script:
  - sudo ./manage.py initdb
  - sudo ./manage.py test