language: python
python:
  - '3.6'

before_script:
  - pip install -r requirements.txt
  - psql -c "CREATE DATABASE purbeurre;" -U postgres
  - psql -c "CREATE USER nmillet WITH PASSWORD 'python123'"
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE purbeurre TO nmillet"
  - psql -c "ALTER USER nmillet CREATEDB"
  - sudo chmod +x ./manage.py
  - ./manage.py migrate
  - ./manage.py initdb

services:
  - postgresql

script:
  - ./manage.py test