# Generated by Django 3.0b1 on 2019-10-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_auto_20191015_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
