# Generated by Django 3.0b1 on 2019-11-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_auto_20191029_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='url', max_length=500),
            preserve_default=False,
        ),
    ]
