# Generated by Django 3.0a1 on 2019-10-15 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=1000)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ingredient', models.TextField(max_length=300, null=True)),
                ('nutriscore', models.CharField(max_length=1)),
                ('store', models.CharField(max_length=30, null=True)),
                ('url', models.URLField(max_length=300)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.Category')),
                ('user_id', models.ManyToManyField(blank=True, related_name='favorites', to='products_app.User')),
            ],
        ),
    ]
