# Generated by Django 3.0a1 on 2019-10-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='favorite',
        ),
    ]
