# Generated by Django 3.0b1 on 2019-10-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_auto_20191029_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id_category',
            new_name='category',
        ),
    ]
