# Generated by Django 3.0b1 on 2020-01-21 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products_app', '0005_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='favorite',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='favorite',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='Products', to='products_app.Product'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='Users', to=settings.AUTH_USER_MODEL),
        ),
    ]
